### ISSUE TITLE
Add an event driven API

### ISSUE THREAD

**Issue by DerAndereAndi** [enbility/cemd#10]
As EEBUS is event driven and all devices can act as server or client for different functionality, the API should reflect that as well. Hence an event driven API should be used, also considering a future Websocket based API to leverage the same style as Go based CEM systems that use this library.

**Comment by wimleers** [comment]
This sounds fantastic!

**Comment by wimleers** [comment]
Is the intent to make it easier for people to start exploring how to use/integrate with/understand EEBus? 

That’s what I assumed, but perhaps mistakenly?

**Comment by DerAndereAndi** [comment]
Yes. And this repository is for "easier" inclusion into a energy management system. One could built another system on top e.g. with a websocket API, and the also none go systems could use it.

**Comment by wimleers** [comment]
Wonderful :) I'd love to experiment, but 23dc02d includes no documentation and is a `+12882,-7554` commit 🤯

**Comment by DerAndereAndi** [comment]
I can't do everything at once ;) Patience, or check the cmd/DemoCem for a start

**Comment by wimleers** [comment]
Of course, I get that! 👍 😊  My $DAYJOB is in open source software too, and there it is disallowed to merge anything without at least high-level documentation/change records.

Apologies if that came across negatively — it was not meant that way! 🙈 I'm just excited/enthusiastic, but parsing a >10K LoC diff just isn't feasible 😅

**Comment by DerAndereAndi** [comment]
It did not come across negatively. I am not getting paid for this work and so far I am alone on it. So I am also trying things out and see if they work, by working on multiple repos at the same time. I am trying to name everything as good as I can, from time to time align the namings, etc. pp. My main focus right now is to get everything working good enough and cover as much as I can with tests.

Documentation will be another hercules task, and I don't think I should do it myself. Otherwise it wouldn't be good enough.

**Comment by wimleers** [comment]
I'm glad to read it didn't come across as I'd feared! 😊 

This entire project is indeed a herculean task. You're right that https://github.com/enbility/cemd/blob/dev/cmd/democem/democem.go is a good starting point. Rather than adding docs for _everything_, two changes would go a long way:
1. Comments in https://github.com/enbility/cemd/blob/dev/cmd/democem/democem.go with `@see`s pointing to other pieces of code, both to document what the current demo app does and what one could _possibly_ build. Encourage curiosity and trial & error! 😊 
2. An `ARCHITECTURE.md` file: https://matklad.github.io/2021/02/06/ARCHITECTURE.md.html

**Comment by DerAndereAndi** [comment]
Feel free to start a discussion or a ticket. And I would be happy to get some help on that :)

**Comment by wimleers** [comment]
I get that! Overloaded myself at the moment though — even though I'd _love_ to dig into this 🤓

For now, I'll be following along from the sidelines — and cheering loudly 😄 🎉
